# Site settings
title: Convergência Livre
description: "Simplificando o compartilhamento da informação."
email: profjulianoramos@gmail.com
baseurl: /
url: "https://convergencialivre.github.io/" # the base hostname & protocol for your site
#favicon
favicon: /favicon.png

#feed
feedburner_username: convergencialivre
#twitter
#twitter_username: #
#github_username:  #

#linkedin
#linkedin_username: pranavrajs

#google analytics
google_analytics_id : UA-53386152-2
#gplus
gplus_username: 101893920934936418705

#fb_username
#fb_username: pranav.tayberrycreative

#permalink /blog/2014/11/11/this-is-a-sample-post
permalink: /blog/:year/:month/:day/:title
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: maangalabscom
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: Prof. Juliano Ramos
    email: profjulianoramos@gmail.com
    fb: julianotux
   # linkedin: pranavrajs
    twitter: profjulianotux
    github: profjulianoramos
